# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The HiFiMagnet Book
email: christophe.trophime@lncmi.cnrs.fr
description: > 
  Non-Linear MultPhysics Modelling for High Field Resistive Magnets
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: feelpp
github_username:  Trophime

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-cayman

gems:
  - jekyll-feed
  - jekyll-asciidoc
exclude:
  - Gemfile
  - Gemfile.lock
  - 0*
  - math/*.tex
  - vendor
  - 00-preface
  - 01-installation
  - 02-docker
  - math/*.adoc

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - allow-uri-read=true
    - idseparator=_
    - source-highlighter=coderay
    - pygments-css=
    - pygments-stylesheet=t
    - icons=font
    - imagesdir=/images
